version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:gallium-bullseye-browsers-legacy
    steps:
      - checkout
      - run: npm install
      - setup_remote_docker
      - run:
          name: Start all services declared in docker-compose.yml
          command: |
            docker-compose up -d
